# Use an official Node.js runtime as a parent image
FROM node:20-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package-lock.json files to the container
COPY package*.json ./

# Install app dependencies
RUN yarn install

# Copy the rest of the application code to the container
COPY . .

# Build the Next.js application without caching
RUN yarn build

# Expose the desired port (e.g., 3000)
EXPOSE 8080

# Run the command to start the Next.js application
CMD ["yarn", "start"]
# Use an official Node.js runtime as a parent image

